/* Auto-generated by modbusAddrMap.py from soc/marble_zest/common/mb_addr_map.toml */
#include <stdint.h>
#include "modbus_registers.h"
#include "localbus.h"
#include "settings.h"
#include "llrf_regs_addr.h"
#include "init_modbus.h"

void mb_autogen_write_callback(int mbRegId, int mbData) {
  enum mb_reg_id id = (enum mb_reg_id)(mbRegId & 0xffff);
  int32_t mbData32 = (int32_t)(mbData & 0xffff);
  switch (id) {
    case MB_INLK_AMP_LO_ADC0:
      write_lb_reg(INLK_AMP_LO_0, mbData32);
      break;
    case MB_INLK_AMP_LO_ADC1:
      write_lb_reg(INLK_AMP_LO_1, mbData32);
      break;
    case MB_INLK_AMP_LO_ADC2:
      write_lb_reg(INLK_AMP_LO_2, mbData32);
      break;
    case MB_INLK_AMP_LO_ADC3:
      write_lb_reg(INLK_AMP_LO_3, mbData32);
      break;
    case MB_INLK_AMP_LO_ADC4:
      write_lb_reg(INLK_AMP_LO_4, mbData32);
      break;
    case MB_INLK_AMP_LO_ADC5:
      write_lb_reg(INLK_AMP_LO_5, mbData32);
      break;
    case MB_INLK_AMP_LO_ADC6:
      write_lb_reg(INLK_AMP_LO_6, mbData32);
      break;
    case MB_INLK_AMP_LO_ADC7:
      write_lb_reg(INLK_AMP_LO_7, mbData32);
      break;
    case MB_INLK_AMP_LO_DAC0:
      write_lb_reg(INLK_AMP_LO_8, mbData32);
      break;
    case MB_INLK_AMP_LO_DAC1:
      write_lb_reg(INLK_AMP_LO_9, mbData32);
      break;
    case MB_INLK_AMP_HI_ADC0:
      write_lb_reg(INLK_AMP_HI_0, mbData32);
      break;
    case MB_INLK_AMP_HI_ADC1:
      write_lb_reg(INLK_AMP_HI_1, mbData32);
      break;
    case MB_INLK_AMP_HI_ADC2:
      write_lb_reg(INLK_AMP_HI_2, mbData32);
      break;
    case MB_INLK_AMP_HI_ADC3:
      write_lb_reg(INLK_AMP_HI_3, mbData32);
      break;
    case MB_INLK_AMP_HI_ADC4:
      write_lb_reg(INLK_AMP_HI_4, mbData32);
      break;
    case MB_INLK_AMP_HI_ADC5:
      write_lb_reg(INLK_AMP_HI_5, mbData32);
      break;
    case MB_INLK_AMP_HI_ADC6:
      write_lb_reg(INLK_AMP_HI_6, mbData32);
      break;
    case MB_INLK_AMP_HI_ADC7:
      write_lb_reg(INLK_AMP_HI_7, mbData32);
      break;
    case MB_INLK_AMP_HI_DAC0:
      write_lb_reg(INLK_AMP_HI_8, mbData32);
      break;
    case MB_INLK_AMP_HI_DAC1:
      write_lb_reg(INLK_AMP_HI_9, mbData32);
      break;
    case MB_INLK_MODE_ADC0:
      write_lb_reg(INLK_INLK_MODE_0, mbData32);
      break;
    case MB_INLK_MODE_ADC1:
      write_lb_reg(INLK_INLK_MODE_1, mbData32);
      break;
    case MB_INLK_MODE_ADC2:
      write_lb_reg(INLK_INLK_MODE_2, mbData32);
      break;
    case MB_INLK_MODE_ADC3:
      write_lb_reg(INLK_INLK_MODE_3, mbData32);
      break;
    case MB_INLK_MODE_ADC4:
      write_lb_reg(INLK_INLK_MODE_4, mbData32);
      break;
    case MB_INLK_MODE_ADC5:
      write_lb_reg(INLK_INLK_MODE_5, mbData32);
      break;
    case MB_INLK_MODE_ADC6:
      write_lb_reg(INLK_INLK_MODE_6, mbData32);
      break;
    case MB_INLK_MODE_ADC7:
      write_lb_reg(INLK_INLK_MODE_7, mbData32);
      break;
    case MB_INLK_MODE_DAC0:
      write_lb_reg(INLK_INLK_MODE_8, mbData32);
      break;
    case MB_INLK_MODE_DAC1:
      write_lb_reg(INLK_INLK_MODE_9, mbData32);
      break;
    case MB_INLK_MASK:
      write_lb_reg(INLK_PERMIT_MASK, mbData32);
      break;
    case MB_INLK_RESET:
      write_lb_reg(INLK_RESET_INLK, mbData32);
      break;
    case MB_LOOP0_KP_AMP:
      write_lb_reg(LOOP0_KP_AMP, mbData32);
      break;
    case MB_LOOP0_KP_AMP_HI:
      mbData32 = (mbData32 << 16) | (int32_t)mb_get_reg_map(MB_LOOP0_KP_AMP);
      write_lb_reg(LOOP0_KP_AMP, mbData32);
      break;
    case MB_LOOP0_KI_AMP:
      write_lb_reg(LOOP0_KI_AMP, mbData32);
      break;
    case MB_LOOP0_KI_AMP_HI:
      mbData32 = (mbData32 << 16) | (int32_t)mb_get_reg_map(MB_LOOP0_KI_AMP);
      write_lb_reg(LOOP0_KI_AMP, mbData32);
      break;
    case MB_LOOP0_KP_PHS:
      write_lb_reg(LOOP0_KP_PHS, mbData32);
      break;
    case MB_LOOP0_KP_PHS_HI:
      mbData32 = (mbData32 << 16) | (int32_t)mb_get_reg_map(MB_LOOP0_KP_PHS);
      write_lb_reg(LOOP0_KP_PHS, mbData32);
      break;
    case MB_LOOP0_KI_PHS:
      write_lb_reg(LOOP0_KI_PHS, mbData32);
      break;
    case MB_LOOP0_KI_PHS_HI:
      mbData32 = (mbData32 << 16) | (int32_t)mb_get_reg_map(MB_LOOP0_KI_PHS);
      write_lb_reg(LOOP0_KI_PHS, mbData32);
      break;
    case MB_LOOP0_AMP_ENABLE:
      write_lb_reg(LOOP0_AMP_ENABLE, mbData32);
      break;
    case MB_LOOP0_PHS_ENABLE:
      write_lb_reg(LOOP0_PHS_ENABLE, mbData32);
      break;
    case MB_LOOP0_AMP_SETPOINT:
      write_lb_reg(LOOP0_AMP_SETPOINT, mbData32);
      break;
    case MB_LOOP0_AMP_SETPOINT_HI:
      mbData32 = (mbData32 << 16) | (int32_t)mb_get_reg_map(MB_LOOP0_AMP_SETPOINT);
      write_lb_reg(LOOP0_AMP_SETPOINT, mbData32);
      break;
    case MB_LOOP0_PHS_SETPOINT:
      write_lb_reg(LOOP0_PHS_SETPOINT, mbData32);
      break;
    case MB_LOOP0_PHS_SETPOINT_HI:
      mbData32 = (mbData32 << 16) | (int32_t)mb_get_reg_map(MB_LOOP0_PHS_SETPOINT);
      write_lb_reg(LOOP0_PHS_SETPOINT, mbData32);
      break;
    case MB_LOOP0_AMP_RESET:
      write_lb_reg(LOOP0_AMP_RESET, mbData32);
      break;
    case MB_LOOP0_PHS_RESET:
      write_lb_reg(LOOP0_PHS_RESET, mbData32);
      break;
    case MB_ARC_PERMIT_MASK:
      write_lb_reg(ARC_PERMIT_MASK, mbData32);
      break;
    case MB_ARC_RESET_ARC_DEV:
      write_lb_reg(ARC_RESET_ARC_DEV, mbData32);
      break;
    case MB_ARC_RESET_LATCH:
      write_lb_reg(ARC_RESET_LATCH, mbData32);
      break;
    case MB_ARC_TEST_MASK:
      write_lb_reg(ARC_TEST_MASK, mbData32);
      break;
    case MB_ARC_TEST_STB:
      write_lb_reg(ARC_TEST_STB, mbData32);
      break;
    case MB_SOFT_DRIVE_ENABLE:
      write_lb_reg(SOFT_DRIVE_ENABLE, mbData32);
      break;
      default:
#ifdef MB_MEMORY_ALLOW_ALL_WRITES
#if MB_MEMORY_ALLOW_ALL_WRITES
          break;
#else // !MB_MEMORY_ALLOW_ALL_WRITES
          return;  // ignore the value for non-writable registers
#endif
#else // ndef MB_MEMORY_ALLOW_ALL_WRITES
          return;  // ignore the value for non-writable registers
#endif
  }
  mb_update_reg_map(id, mbData); // store the value for writable registers
  return;
}

void mb_autogen_reg_update(void) {
  int32_t val;
  /* Read-Only Registers */
  val = read_lb_reg(MON_AMP_0);
  mb_update_reg_map(MB_ADC0_MON_AMP, val);
  val = read_lb_reg(MON_AMP_1);
  mb_update_reg_map(MB_ADC1_MON_AMP, val);
  val = read_lb_reg(MON_AMP_2);
  mb_update_reg_map(MB_ADC2_MON_AMP, val);
  val = read_lb_reg(MON_AMP_3);
  mb_update_reg_map(MB_ADC3_MON_AMP, val);
  val = read_lb_reg(MON_AMP_4);
  mb_update_reg_map(MB_ADC4_MON_AMP, val);
  val = read_lb_reg(MON_AMP_5);
  mb_update_reg_map(MB_ADC5_MON_AMP, val);
  val = read_lb_reg(MON_AMP_6);
  mb_update_reg_map(MB_ADC6_MON_AMP, val);
  val = read_lb_reg(MON_AMP_7);
  mb_update_reg_map(MB_ADC7_MON_AMP, val);
  val = read_lb_reg(MON_AMP_8);
  mb_update_reg_map(MB_DAC0_MON_AMP, val);
  val = read_lb_reg(MON_AMP_9);
  mb_update_reg_map(MB_DAC1_MON_AMP, val);
  val = read_lb_reg(MON_PHS_0);
  mb_update_reg_map(MB_ADC0_MON_PHS, val & 0xffff);
  mb_update_reg_map(MB_ADC0_MON_PHS_HI, val>>16);
  val = read_lb_reg(MON_PHS_1);
  mb_update_reg_map(MB_ADC1_MON_PHS, val & 0xffff);
  mb_update_reg_map(MB_ADC1_MON_PHS_HI, val>>16);
  val = read_lb_reg(MON_PHS_2);
  mb_update_reg_map(MB_ADC2_MON_PHS, val & 0xffff);
  mb_update_reg_map(MB_ADC2_MON_PHS_HI, val>>16);
  val = read_lb_reg(MON_PHS_3);
  mb_update_reg_map(MB_ADC3_MON_PHS, val & 0xffff);
  mb_update_reg_map(MB_ADC3_MON_PHS_HI, val>>16);
  val = read_lb_reg(MON_PHS_4);
  mb_update_reg_map(MB_ADC4_MON_PHS, val & 0xffff);
  mb_update_reg_map(MB_ADC4_MON_PHS_HI, val>>16);
  val = read_lb_reg(MON_PHS_5);
  mb_update_reg_map(MB_ADC5_MON_PHS, val & 0xffff);
  mb_update_reg_map(MB_ADC5_MON_PHS_HI, val>>16);
  val = read_lb_reg(MON_PHS_6);
  mb_update_reg_map(MB_ADC6_MON_PHS, val & 0xffff);
  mb_update_reg_map(MB_ADC6_MON_PHS_HI, val>>16);
  val = read_lb_reg(MON_PHS_7);
  mb_update_reg_map(MB_ADC7_MON_PHS, val & 0xffff);
  mb_update_reg_map(MB_ADC7_MON_PHS_HI, val>>16);
  val = read_lb_reg(MON_PHS_8);
  mb_update_reg_map(MB_DAC0_MON_PHS, val & 0xffff);
  mb_update_reg_map(MB_DAC0_MON_PHS_HI, val>>16);
  val = read_lb_reg(MON_PHS_9);
  mb_update_reg_map(MB_DAC1_MON_PHS, val & 0xffff);
  mb_update_reg_map(MB_DAC1_MON_PHS_HI, val>>16);
  val = read_lb_reg(RF_PWR_FIRST_FAULT_STATUS);
  mb_update_reg_map(MB_INLK_FIRST_FAULT_STATUS, val);
  val = read_lb_reg(RF_PWR_STATUS);
  mb_update_reg_map(MB_INLK_STATUS, val);
  val = read_lb_reg(RF_PWR_PERMIT_SUM);
  mb_update_reg_map(MB_INLK_PERMIT, val);
  val = read_lb_reg(RF_PWR_LATCH);
  mb_update_reg_map(MB_INLK_LATCH, val);
  val = read_lb_reg(RF_PWR_HI);
  mb_update_reg_map(MB_INLK_HI, val);
  val = read_lb_reg(RF_PWR_LO);
  mb_update_reg_map(MB_INLK_LO, val);
  val = read_lb_reg(ARC_PERMIT_LATCH);
  mb_update_reg_map(MB_ARC_PERMIT_LATCH, val);
  val = read_lb_reg(ARC_PERMIT_RAW);
  mb_update_reg_map(MB_ARC_PERMIT_RAW, val);
  val = read_lb_reg(ARC_PERMIT_SUM);
  mb_update_reg_map(MB_ARC_PERMIT_SUM, val);
  val = read_lb_reg(DRIVE_PERMIT_IN);
  mb_update_reg_map(MB_DRIVE_PERMIT_IN, val);
  val = read_lb_reg(SLOW_PERMIT_IN);
  mb_update_reg_map(MB_SLOW_PERMIT_IN, val);
  val = read_lb_reg(FAST_PERMIT_OUT);
  mb_update_reg_map(MB_FAST_PERMIT, val);
  val = read_lb_reg(HPA_PERMIT_OUT);
  mb_update_reg_map(MB_HPA_PERMIT, val);
  val = read_lb_reg(EVG_PERMIT_OUT);
  mb_update_reg_map(MB_EVG_PERMIT_OUT, val);
  val = read_lb_reg(DRIVE_PERMIT_OUT);
  mb_update_reg_map(MB_DRIVE_PERMIT_OUT, val);
  /* Read-Write Registers */
  val = read_lb_reg(INLK_AMP_LO_0);
  mb_update_reg_map(MB_INLK_AMP_LO_ADC0, val);
  val = read_lb_reg(INLK_AMP_LO_1);
  mb_update_reg_map(MB_INLK_AMP_LO_ADC1, val);
  val = read_lb_reg(INLK_AMP_LO_2);
  mb_update_reg_map(MB_INLK_AMP_LO_ADC2, val);
  val = read_lb_reg(INLK_AMP_LO_3);
  mb_update_reg_map(MB_INLK_AMP_LO_ADC3, val);
  val = read_lb_reg(INLK_AMP_LO_4);
  mb_update_reg_map(MB_INLK_AMP_LO_ADC4, val);
  val = read_lb_reg(INLK_AMP_LO_5);
  mb_update_reg_map(MB_INLK_AMP_LO_ADC5, val);
  val = read_lb_reg(INLK_AMP_LO_6);
  mb_update_reg_map(MB_INLK_AMP_LO_ADC6, val);
  val = read_lb_reg(INLK_AMP_LO_7);
  mb_update_reg_map(MB_INLK_AMP_LO_ADC7, val);
  val = read_lb_reg(INLK_AMP_LO_8);
  mb_update_reg_map(MB_INLK_AMP_LO_DAC0, val);
  val = read_lb_reg(INLK_AMP_LO_9);
  mb_update_reg_map(MB_INLK_AMP_LO_DAC1, val);
  val = read_lb_reg(INLK_AMP_HI_0);
  mb_update_reg_map(MB_INLK_AMP_HI_ADC0, val);
  val = read_lb_reg(INLK_AMP_HI_1);
  mb_update_reg_map(MB_INLK_AMP_HI_ADC1, val);
  val = read_lb_reg(INLK_AMP_HI_2);
  mb_update_reg_map(MB_INLK_AMP_HI_ADC2, val);
  val = read_lb_reg(INLK_AMP_HI_3);
  mb_update_reg_map(MB_INLK_AMP_HI_ADC3, val);
  val = read_lb_reg(INLK_AMP_HI_4);
  mb_update_reg_map(MB_INLK_AMP_HI_ADC4, val);
  val = read_lb_reg(INLK_AMP_HI_5);
  mb_update_reg_map(MB_INLK_AMP_HI_ADC5, val);
  val = read_lb_reg(INLK_AMP_HI_6);
  mb_update_reg_map(MB_INLK_AMP_HI_ADC6, val);
  val = read_lb_reg(INLK_AMP_HI_7);
  mb_update_reg_map(MB_INLK_AMP_HI_ADC7, val);
  val = read_lb_reg(INLK_AMP_HI_8);
  mb_update_reg_map(MB_INLK_AMP_HI_DAC0, val);
  val = read_lb_reg(INLK_AMP_HI_9);
  mb_update_reg_map(MB_INLK_AMP_HI_DAC1, val);
  val = read_lb_reg(INLK_INLK_MODE_0);
  mb_update_reg_map(MB_INLK_MODE_ADC0, val);
  val = read_lb_reg(INLK_INLK_MODE_1);
  mb_update_reg_map(MB_INLK_MODE_ADC1, val);
  val = read_lb_reg(INLK_INLK_MODE_2);
  mb_update_reg_map(MB_INLK_MODE_ADC2, val);
  val = read_lb_reg(INLK_INLK_MODE_3);
  mb_update_reg_map(MB_INLK_MODE_ADC3, val);
  val = read_lb_reg(INLK_INLK_MODE_4);
  mb_update_reg_map(MB_INLK_MODE_ADC4, val);
  val = read_lb_reg(INLK_INLK_MODE_5);
  mb_update_reg_map(MB_INLK_MODE_ADC5, val);
  val = read_lb_reg(INLK_INLK_MODE_6);
  mb_update_reg_map(MB_INLK_MODE_ADC6, val);
  val = read_lb_reg(INLK_INLK_MODE_7);
  mb_update_reg_map(MB_INLK_MODE_ADC7, val);
  val = read_lb_reg(INLK_INLK_MODE_8);
  mb_update_reg_map(MB_INLK_MODE_DAC0, val);
  val = read_lb_reg(INLK_INLK_MODE_9);
  mb_update_reg_map(MB_INLK_MODE_DAC1, val);
  val = read_lb_reg(INLK_PERMIT_MASK);
  mb_update_reg_map(MB_INLK_MASK, val);
  val = read_lb_reg(INLK_RESET_INLK);
  mb_update_reg_map(MB_INLK_RESET, val);
  val = read_lb_reg(LOOP0_KP_AMP);
  mb_update_reg_map(MB_LOOP0_KP_AMP, val & 0xffff);
  mb_update_reg_map(MB_LOOP0_KP_AMP_HI, val>>16);
  val = read_lb_reg(LOOP0_KI_AMP);
  mb_update_reg_map(MB_LOOP0_KI_AMP, val & 0xffff);
  mb_update_reg_map(MB_LOOP0_KI_AMP_HI, val>>16);
  val = read_lb_reg(LOOP0_KP_PHS);
  mb_update_reg_map(MB_LOOP0_KP_PHS, val & 0xffff);
  mb_update_reg_map(MB_LOOP0_KP_PHS_HI, val>>16);
  val = read_lb_reg(LOOP0_KI_PHS);
  mb_update_reg_map(MB_LOOP0_KI_PHS, val & 0xffff);
  mb_update_reg_map(MB_LOOP0_KI_PHS_HI, val>>16);
  val = read_lb_reg(LOOP0_AMP_ENABLE);
  mb_update_reg_map(MB_LOOP0_AMP_ENABLE, val);
  val = read_lb_reg(LOOP0_PHS_ENABLE);
  mb_update_reg_map(MB_LOOP0_PHS_ENABLE, val);
  val = read_lb_reg(LOOP0_AMP_SETPOINT);
  mb_update_reg_map(MB_LOOP0_AMP_SETPOINT, val & 0xffff);
  mb_update_reg_map(MB_LOOP0_AMP_SETPOINT_HI, val>>16);
  val = read_lb_reg(LOOP0_PHS_SETPOINT);
  mb_update_reg_map(MB_LOOP0_PHS_SETPOINT, val & 0xffff);
  mb_update_reg_map(MB_LOOP0_PHS_SETPOINT_HI, val>>16);
  val = read_lb_reg(LOOP0_AMP_RESET);
  mb_update_reg_map(MB_LOOP0_AMP_RESET, val);
  val = read_lb_reg(LOOP0_PHS_RESET);
  mb_update_reg_map(MB_LOOP0_PHS_RESET, val);
  val = read_lb_reg(ARC_PERMIT_MASK);
  mb_update_reg_map(MB_ARC_PERMIT_MASK, val);
  val = read_lb_reg(ARC_RESET_ARC_DEV);
  mb_update_reg_map(MB_ARC_RESET_ARC_DEV, val);
  val = read_lb_reg(ARC_RESET_LATCH);
  mb_update_reg_map(MB_ARC_RESET_LATCH, val);
  val = read_lb_reg(ARC_TEST_MASK);
  mb_update_reg_map(MB_ARC_TEST_MASK, val);
  val = read_lb_reg(ARC_TEST_STB);
  mb_update_reg_map(MB_ARC_TEST_STB, val);
  val = read_lb_reg(SOFT_DRIVE_ENABLE);
  mb_update_reg_map(MB_SOFT_DRIVE_ENABLE, val);
  return;
}
