#ifndef _MODBUS_REGISTERS_H
#define __MODBUS_REGISTERS_H
/* Auto-generated by modbusAddrMap.py from soc/marble_zest/common/mb_addr_map.toml */

void mb_autogen_write_callback(int mbRegId, int mbData);
void mb_autogen_reg_update(void);

enum mb_reg_id {
  /* Read-Only Registers */
  MB_ADC0_MON_AMP,                         /* 0 */
  MB_ADC1_MON_AMP,                         /* 1 */
  MB_ADC2_MON_AMP,                         /* 2 */
  MB_ADC3_MON_AMP,                         /* 3 */
  MB_ADC4_MON_AMP,                         /* 4 */
  MB_ADC5_MON_AMP,                         /* 5 */
  MB_ADC6_MON_AMP,                         /* 6 */
  MB_ADC7_MON_AMP,                         /* 7 */
  MB_DAC0_MON_AMP,                         /* 8 */
  MB_DAC1_MON_AMP,                         /* 9 */
  MB_ADC0_MON_PHS,                         /* 10 */
  MB_ADC0_MON_PHS_HI,                      /* 11 */
  MB_ADC1_MON_PHS,                         /* 12 */
  MB_ADC1_MON_PHS_HI,                      /* 13 */
  MB_ADC2_MON_PHS,                         /* 14 */
  MB_ADC2_MON_PHS_HI,                      /* 15 */
  MB_ADC3_MON_PHS,                         /* 16 */
  MB_ADC3_MON_PHS_HI,                      /* 17 */
  MB_ADC4_MON_PHS,                         /* 18 */
  MB_ADC4_MON_PHS_HI,                      /* 19 */
  MB_ADC5_MON_PHS,                         /* 20 */
  MB_ADC5_MON_PHS_HI,                      /* 21 */
  MB_ADC6_MON_PHS,                         /* 22 */
  MB_ADC6_MON_PHS_HI,                      /* 23 */
  MB_ADC7_MON_PHS,                         /* 24 */
  MB_ADC7_MON_PHS_HI,                      /* 25 */
  MB_DAC0_MON_PHS,                         /* 26 */
  MB_DAC0_MON_PHS_HI,                      /* 27 */
  MB_DAC1_MON_PHS,                         /* 28 */
  MB_DAC1_MON_PHS_HI,                      /* 29 */
  MB_INLK_FIRST_FAULT_STATUS,              /* 30 */
  MB_INLK_STATUS,                          /* 31 */
  MB_INLK_PERMIT,                          /* 32 */
  MB_INLK_LATCH,                           /* 33 */
  MB_INLK_HI,                              /* 34 */
  MB_INLK_LO,                              /* 35 */
  MB_ARC_PERMIT_LATCH,                     /* 36 */
  MB_ARC_PERMIT_RAW,                       /* 37 */
  MB_ARC_PERMIT_SUM,                       /* 38 */
  MB_DRIVE_PERMIT_IN,                      /* 39 */
  MB_SLOW_PERMIT_IN,                       /* 40 */
  MB_FAST_PERMIT,                          /* 41 */
  MB_HPA_PERMIT,                           /* 42 */
  MB_EVG_PERMIT_OUT,                       /* 43 */
  MB_DRIVE_PERMIT_OUT,                     /* 44 */
  /* Read-Write Registers */
  MB_INLK_AMP_LO_ADC0,                     /* 45 */
  MB_INLK_AMP_LO_ADC1,                     /* 46 */
  MB_INLK_AMP_LO_ADC2,                     /* 47 */
  MB_INLK_AMP_LO_ADC3,                     /* 48 */
  MB_INLK_AMP_LO_ADC4,                     /* 49 */
  MB_INLK_AMP_LO_ADC5,                     /* 50 */
  MB_INLK_AMP_LO_ADC6,                     /* 51 */
  MB_INLK_AMP_LO_ADC7,                     /* 52 */
  MB_INLK_AMP_LO_DAC0,                     /* 53 */
  MB_INLK_AMP_LO_DAC1,                     /* 54 */
  MB_INLK_AMP_HI_ADC0,                     /* 55 */
  MB_INLK_AMP_HI_ADC1,                     /* 56 */
  MB_INLK_AMP_HI_ADC2,                     /* 57 */
  MB_INLK_AMP_HI_ADC3,                     /* 58 */
  MB_INLK_AMP_HI_ADC4,                     /* 59 */
  MB_INLK_AMP_HI_ADC5,                     /* 60 */
  MB_INLK_AMP_HI_ADC6,                     /* 61 */
  MB_INLK_AMP_HI_ADC7,                     /* 62 */
  MB_INLK_AMP_HI_DAC0,                     /* 63 */
  MB_INLK_AMP_HI_DAC1,                     /* 64 */
  MB_INLK_MODE_ADC0,                       /* 65 */
  MB_INLK_MODE_ADC1,                       /* 66 */
  MB_INLK_MODE_ADC2,                       /* 67 */
  MB_INLK_MODE_ADC3,                       /* 68 */
  MB_INLK_MODE_ADC4,                       /* 69 */
  MB_INLK_MODE_ADC5,                       /* 70 */
  MB_INLK_MODE_ADC6,                       /* 71 */
  MB_INLK_MODE_ADC7,                       /* 72 */
  MB_INLK_MODE_DAC0,                       /* 73 */
  MB_INLK_MODE_DAC1,                       /* 74 */
  MB_INLK_MASK,                            /* 75 */
  MB_INLK_RESET,                           /* 76 */
  MB_LOOP0_KP_AMP,                         /* 77 */
  MB_LOOP0_KP_AMP_HI,                      /* 78 */
  MB_LOOP0_KI_AMP,                         /* 79 */
  MB_LOOP0_KI_AMP_HI,                      /* 80 */
  MB_LOOP0_KP_PHS,                         /* 81 */
  MB_LOOP0_KP_PHS_HI,                      /* 82 */
  MB_LOOP0_KI_PHS,                         /* 83 */
  MB_LOOP0_KI_PHS_HI,                      /* 84 */
  MB_LOOP0_AMP_ENABLE,                     /* 85 */
  MB_LOOP0_PHS_ENABLE,                     /* 86 */
  MB_LOOP0_AMP_SETPOINT,                   /* 87 */
  MB_LOOP0_AMP_SETPOINT_HI,                /* 88 */
  MB_LOOP0_PHS_SETPOINT,                   /* 89 */
  MB_LOOP0_PHS_SETPOINT_HI,                /* 90 */
  MB_LOOP0_AMP_RESET,                      /* 91 */
  MB_LOOP0_PHS_RESET,                      /* 92 */
  MB_ARC_PERMIT_MASK,                      /* 93 */
  MB_ARC_RESET_ARC_DEV,                    /* 94 */
  MB_ARC_RESET_LATCH,                      /* 95 */
  MB_ARC_TEST_MASK,                        /* 96 */
  MB_ARC_TEST_STB,                         /* 97 */
  MB_SOFT_DRIVE_ENABLE,                    /* 98 */
  /* Special Registers */
  MB_FPGA_UP,                              /* 99 */
  MB_FPGA_TEMP,                            /* 100 */
  MB_FPGA_VCCINT,                          /* 101 */
  MB_FPGA_VCCAUX,                          /* 102 */
  MB_FPGA_VCCBRAM,                         /* 103 */
  MB_REG_MAP_LEN /* End of enum */
};
// Max: 104 = 0x68

#endif /* ndef __MODBUS_REGISTERS_H */
