from litex_boards.platforms import berkeleylab_marble
from litex.build.openocd import OpenOCD
import argparse
import os
import json
import zlib
import struct

platform = "berkeleylab_marble"

def mkimg_firmware(i_fname):
    '''
    Prepare firmware image by inserting at head:
    4 bytes of length
    4 bytes of crc
    see bios/boot.c check_image_in_flash()
    '''
    data = open(i_fname, 'rb').read()
    size = len(data)
    crc32 = zlib.crc32(data)
    print(f'Binary file {i_fname} found,'
          f'size = {size:#x} crc= {crc32:#x}.')
    o_fname = 'boot_image.bin'
    with open(o_fname, 'wb') as f:
        f.write(struct.pack('<L', size))
        f.write(struct.pack('<L', crc32))
        f.write(data)
    return o_fname


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Flash tool')
    parser.add_argument('--conf_file', default='csr.json',
                        help='JSON configuration generated by LiteX')
    parser.add_argument("--mode", default="firmware",
                        choices=["gateware", "firmware"],
                        help="Type of file to flash")
    parser.add_argument("--dryrun", action="store_true",
                        help="execute without programming flash")
    args = parser.parse_args()

    if args.mode == 'gateware':
        filename = os.path.join('build', platform, 'gateware', f'{platform}.bin')
        address_start = 0  # XXX pay attention to OTP of S25FL128S
    elif args.mode == 'firmware':
        with open(args.conf_file) as f:
            csr = json.load(f)
        assert ('flash_boot_address' in csr['constants'])
        assert ('spiflash' in csr['memories'])
        address_start = csr['constants']['flash_boot_address'] - \
            csr['memories']['spiflash']['base']
        assert (address_start >= 0x800_000)  # don't override gateware
        filename = mkimg_firmware(os.path.join('firmware', 'firmware.bin'))

    assert (os.path.exists(filename))

    print(f"Programming {filename} at {address_start:#x}...")
    if not args.dryrun:
        # prog = berkeleylab_marble.Platform().create_programmer()
        prog = OpenOCD("prog/openocd_marble.cfg", flash_proxy_basename="bscan_spi_xc7k160t.bit")
        prog.flash(address_start, filename)
        if args.mode == 'firmware':
            os.remove(filename)
