stages:
  - test
  - synthesis
  - run

variables:
  XILINX_VIVADO: /non-free/Xilinx/Vivado_and_Vitis/2022.1/Vivado/2022.1
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: normal

image: mohs.dhcp.lbl.gov/xilinx_env_trixie

flake8:
  stage: test
  script:
   - flake8 python llrf_dsp

llrf_dsp_test:
  before_script:
    - pip install numpy scipy cocotb==1.9.2 pytest cocotb-bus
    - cd llrf_dsp
  stage: test
  script:
    - make FSET=${TARGET}
  parallel:
    matrix:
      - TARGET: [LEMP]

llrf_cdc_test:
  before_script:
    - cd llrf_dsp
  stage: test
  script:
    - make llrf_shell_expand.v && make llrf_shell_cdc.txt
  artifacts:
    when: always
    paths:
      - llrf_dsp/llrf_shell_cdc.txt

marble_bsp_test:
  before_script:
    - cd marble_bsp
  stage: test
  script:
    - make

marble_zest_synth:
  before_script:
    - cd top/marble_zest
  stage: synthesis
  script:
    - PATH=$XILINX_VIVADO/bin:$PATH make FSET=${TARGET}
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 2 days
    paths:
      - top/marble_zest/*.bit
      - top/marble_zest/*.bin
      - top/marble_zest/_xilinx/*.runs/impl_1/*.rpt
  parallel:
    matrix:
      - TARGET: [ALSU, USPAS, LEMP, AWA]

.marble_lemp_run:
  before_script:
    - pip install pandas
    - cd top/marble_zest
  stage: run
  tags:
    - deploy
  needs:
  - job: marble_zest_synth
    parallel:
      matrix:
        - PLATFORM: LEMP
  script:
    - make system_config MARBLE_SERIAL=42 FSET=LEMP && sleep 4 && make system_test MARBLE_SERIAL=42

.marble_awa_run:
  before_script:
    - pip install pandas
    - cd top/marble_zest
  stage: run
  tags:
    - deploy
  needs:
  - job: marble_zest_synth
    parallel:
      matrix:
        - PLATFORM: AWA
  script:
    - make system_config MARBLE_SERIAL=39 FSET=AWA && sleep 4 && make system_test MARBLE_SERIAL=39

.marble_uspas_run:
  before_script:
    - pip install pandas
    - cd top/marble_zest
  stage: run
  tags:
    - deploy
  needs:
  - job: marble_zest_synth
    parallel:
      matrix:
        - PLATFORM: USPAS
  script:
    - make system_config MARBLE_SERIAL=42 FSET=USPAS && sleep 4 && make system_test MARBLE_SERIAL=42
