stages:
  - test
  - synthesis
  - run

variables:
  XILINX_VIVADO: /non-free/Xilinx/Vivado/2020.2
  CI_REGISTRY: mohs.dhcp.lbl.gov
  CONTAINER_IMAGE: $CI_REGISTRY/testing_base_bookworm
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: normal

image: $CONTAINER_IMAGE:master

llrf_dsp_test_alsu:
  before_script:
    - cd llrf_dsp
  stage: test
  script:
    - make clean && make FSET=ALSU

llrf_dsp_test_uspas:
  before_script:
    - cd llrf_dsp
  stage: test
  script:
    - make clean && make FSET=USPAS

llrf_dsp_test_lemp:
  before_script:
    - cd llrf_dsp
  stage: test
  script:
    - make clean && make FSET=LEMP

cocotb_dsp_test:
  before_script:
    - apt-get install verilator
    - pip install numpy scipy cocotb pytest
    - cd llrf_dsp/tests
  stage: test
  script:
    - make

llrf_cdc_test:
  before_script:
    - cd llrf_dsp
  stage: test
  script:
    - make clean && make llrf_shell_expand.v && make llrf_shell_cdc.txt
  artifacts:
    when: always
    paths:
      - llrf_dsp/llrf_shell_cdc.txt

marble_zest_lemp_synth:
  before_script:
    - cd top/marble_zest
  stage: synthesis
  script:
    - make clean && PATH=$XILINX_VIVADO/bin:$PATH make marble_zest_top.bit
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 2 days
    paths:
      - top/marble_zest/lemp/marble_zest_top.bit
      - top/marble_zest/lemp/_xilinx/marble_zest_top/*.runs/impl_1/*.rpt

marble_zest_alsu_synth:
  before_script:
    - cd top/marble_zest
  stage: synthesis
  script:
    - make clean && PATH=$XILINX_VIVADO/bin:$PATH make FSET=ALSU marble_zest_top.bit
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 2 days
    paths:
      - top/marble_zest/alsu/marble_zest_top.bit
      - top/marble_zest/alsu/_xilinx/marble_zest_top/*.runs/impl_1/*.rpt


marble_run:
  before_script:
    - cd top/marble_zest
  stage: run
  tags:
    - deploy
  dependencies:
    - marble_zest_lemp_synth
  script:
    - make system_config MARBLE_SERIAL=42 && make system_test MARBLE_SERIAL=42
