# details see README.md
# choice from ALSU, USPAS, LEMP, AWA
FSET = LEMP

CFG_ALSU_DSP_FREQ_MHZ  = 114.58
CFG_USPAS_DSP_FREQ_MHZ = 115.0
CFG_LEMP_DSP_FREQ_MHZ  = 119.0
CFG_AWA_DSP_FREQ_MHZ   = 94.285

CFG_LEMP_EVR_GTX_REF_FREQ_MHZ = 119.0
CFG_USPAS_EVR_GTX_REF_FREQ_MHZ = 125.0
CFG_ALSU_EVR_GTX_REF_FREQ_MHZ = 125.1
CFG_AWA_EVR_GTX_REF_FREQ_MHZ = 125.0

# LEMP requires 93.5MHz DAC output, 1/(2*cos(omega)) where omega = 2*pi*11/28
CFG_ALSU_DAC_INTERP_COEFF_R = 1.0
CFG_USPAS_DAC_INTERP_COEFF_R = 1.0
CFG_LEMP_DAC_INTERP_COEFF_R = -1.279
CFG_AWA_DAC_INTERP_COEFF_R = 1.0

SYNTH_OPT   += -DDSP_FREQ_MHZ=$(CFG_$(FSET)_DSP_FREQ_MHZ)
SYNTH_OPT   += -DEVR_GTX_REF_FREQ_MHZ=$(CFG_$(FSET)_EVR_GTX_REF_FREQ_MHZ)
SYNTH_OPT   += -DDAC_INTERP_COEFF_R=$(CFG_$(FSET)_DAC_INTERP_COEFF_R)
CFLAGS      += -DDSP_FREQ_MHZ=$(CFG_$(FSET)_DSP_FREQ_MHZ)
CFLAGS      += -DEVR_GTX_REF_FREQ_MHZ=$(CFG_$(FSET)_EVR_GTX_REF_FREQ_MHZ)

# Serial number of Marble board, 6 digits
MARBLE_SERIAL = 122
MARBLE_SN = $(shell printf %06d $(MARBLE_SERIAL))
