# details see README.md
# DESGIN in [uspas, alsu, lemp, awa{0,1}, pip-ii, vts]
# FSET in [ALSU, USPAS, LEMP, AWA]
# map from DESIGN to FSET
DESIGN ?= uspas

FSET_uspas = USPAS
FSET_alsu  = ALSU
FSET_lemp  = LEMP
FSET_awa   = AWA
FSET_awa0  = AWA
FSET_awa1  = AWA
FSET_pip-ii= AWA
FSET_vts   = AWA

FSET := $(FSET_$(DESIGN))

CFG_ALSU_DSP_FREQ_MHZ  = 114.58
CFG_USPAS_DSP_FREQ_MHZ = 115.0
CFG_LEMP_DSP_FREQ_MHZ  = 119.0
CFG_AWA_DSP_FREQ_MHZ   = 94.285

CFG_ALSU_EVR_GT_REF_FREQ_MHZ  = 125.1
CFG_USPAS_EVR_GT_REF_FREQ_MHZ = 125.0
CFG_LEMP_EVR_GT_REF_FREQ_MHZ  = 119.0
CFG_AWA_EVR_GT_REF_FREQ_MHZ   = 125.0

SYNTH_OPT   += -DDSP_FREQ_MHZ=$(CFG_$(FSET)_DSP_FREQ_MHZ)
SYNTH_OPT   += -DEVR_GT_REF_FREQ_MHZ=$(CFG_$(FSET)_EVR_GT_REF_FREQ_MHZ)
CFLAGS      += -DDSP_FREQ_MHZ=$(CFG_$(FSET)_DSP_FREQ_MHZ)
CFLAGS      += -DEVR_GT_REF_FREQ_MHZ=$(CFG_$(FSET)_EVR_GT_REF_FREQ_MHZ)

# Serial number of Marble board, 6 digits
MARBLE_SERIAL = 122
MARBLE_SN = $(shell printf %06d $(MARBLE_SERIAL))
