# details see README.md
# choice from ALSU, USPAS, LEMP
FSET = LEMP

CFG_ALSU_DSP_FREQ_MHZ  = 114.58
CFG_USPAS_DSP_FREQ_MHZ = 115.0
CFG_LEMP_DSP_FREQ_MHZ  = 119.0

# LEMP requires 93.5MHz DAC output, 1/(2*cos(omega)) where omega = 2*pi*11/28
CFG_ALSU_DAC_INTERP_COEFF_R = 1.0
CFG_USPAS_DAC_INTERP_COEFF_R = 1.0
CFG_LEMP_DAC_INTERP_COEFF_R = -1.279

SYNTH_OPT   += -DDSP_FREQ_MHZ=$(CFG_$(FSET)_DSP_FREQ_MHZ)
SYNTH_OPT   += -DDAC_INTERP_COEFF_R=$(CFG_$(FSET)_DAC_INTERP_COEFF_R)
CFLAGS      += -DDSP_FREQ_MHZ=$(CFG_$(FSET)_DSP_FREQ_MHZ)

# Serial number of Marble board
MARBLE_SERIAL = 122
