# Generate address mapping for modbus-accessible registers
# Generate the C code for picorv32 modbus driver

import os
import sys
import tomli as toml


def get_addr_map(filepath):
    with open(filepath, 'rb') as fd:
        _map = toml.load(fd)
    return _map


def toml_test(filepath):
    _map = get_addr_map(filepath)
    print(_map)
    return


global __THIS_FILE__
__THIS_FILE__ = "modbusAddrMap.py"  # This will be clobbered and is just a fallback value


class CGenerator():
    def __init__(self, filepath):
        self._addr_map = self._get_leep_map(filepath)
        self._ro = self._addr_map.get("ro", None)
        self._rw = self._addr_map.get("rw", None)
        self._sp = self._addr_map.get("special", None)
        self._input_file = filepath
        self._written = []
        self._write_fn_sig = "void mb_autogen_write_callback(int mbRegId, int mbData)"
        self._read_fn_sig = "void mb_autogen_reg_update(void)"
        self._default_header_name = "modbus_registers.h"
        self._header_name = self._default_header_name  # clobber me
        self._default_source_name = "modbus_bus_handlers.c"
        self._default_includes = ("localbus.h", "settings.h")
        self._includes = None

    def add_include(self, include_file):
        if self._includes is None:
            self._includes = []
        self._includes.append(include_file)
        return

    def _get_leep_map(self, filepath):
        _map = get_addr_map(filepath)
        # Stage 1, dict of {leep_register_name: (mb_name, offset, isword), }
        for section, _dict in _map.items():
            dd = {}
            for key, leep_data in _dict.items():
                mb_name = f"MB_{key.upper()}"
                isword = leep_data[2]
                offset = leep_data[1]
                # I need to get this right; the naming convention is determined by a separate script!
                reg_list = dd.get(leep_data[0], [])
                reg_list.append((mb_name, offset, isword))
                dd[leep_data[0]] = reg_list
            _map[section] = dd
        # Stage 2, dict of {mb_name: (LEEP_AUTOGEN_C_NAME, is_upper), }
        for section, _dict in _map.items():
            dd = {}
            for leep_reg, data in _dict.items():
                for n in range(len(data)):
                    mb_name, offset, isword = data[n]
                    if not hasattr(leep_reg, "upper"):
                        leep_name = None
                    else:
                        if len(data) == 1:
                            leep_name = leep_reg.upper()
                        else:
                            leep_name = leep_reg.upper() + f"_{offset}"
                    dd[mb_name] = (leep_name, False)
                    if isword:
                        dd[self.get_high_mb_name(mb_name)] = (leep_name, True)
            _map[section] = dd
        return _map

    def _init_filepath(self, filepath, default):
        initialized = False
        if filepath is None:
            self._fp = None
            fname = default
            if filepath in self._written:
                initialized = True
            else:
                self._written.append(filepath)
        else:
            if filepath in self._written:
                self._fp = open(filepath, "a")
                initialized = True
            else:
                self._written.append(filepath)
                self._fp = open(filepath, "w")
            fpath, fname = os.path.split(filepath)
        return fname, initialized

    def _w(self, *args, **kwargs):
        if self._fp is None:
            fp = sys.stdout
        else:
            fp = self._fp
        print(*args, **kwargs, file=fp)
        return

    def gen_header(self, filepath=None):
        fname, initialized = self._init_filepath(filepath, self._default_header_name)
        self._header_name = fname
        hh = "_" + fname.upper().replace('.', '_')
        self._w(f"#ifndef {hh}")
        self._w(f"#define _{hh}")
        self._w(f"/* Auto-generated by {__THIS_FILE__} from {self._input_file} */")
        self._w()
        self._w(f"{self._write_fn_sig};")
        self._w(f"{self._read_fn_sig};")
        self._w()
        self._w("enum mb_reg_id {")
        enum_index = 0
        todo = (
            (self._ro, "Read-Only Registers"),
            (self._rw, "Read-Write Registers"),
            (self._sp, "Special Registers"),
        )
        for _map, comment in todo:
            if len(_map) == 0:
                print(f"Skipping {comment}")
                continue
            self._w(f"  /* {comment} */")
            for mb_name, (leep_name, is_upper) in _map.items():
                mb_name += ","
                self._w(f"  {mb_name:<40} /* {enum_index} */")
                enum_index += 1
        self._w("  MB_REG_MAP_LEN /* End of enum */")
        self._w("};")
        self._w(f"// Max: {enum_index} = 0x{enum_index:x}")
        self._w(f"\n#endif /* ndef _{hh} */")
        if self._fp is not None:
            self._fp.close()
        return

    def _source_init(self, filename, header_names=None):
        self._w(f"/* Auto-generated by {__THIS_FILE__} from {self._input_file} */")
        self._w("#include <stdint.h>")
        self._w(f"#include \"{self._header_name}\"")
        if self._includes is None:
            includes = self._default_includes
        else:
            includes = self._includes
        if header_names is None:
            header_names = includes
        for header_name in header_names:
            self._w(f"#include \"{header_name}\"")
        return

    def gen_write_fn(self, filepath=None, includes=None):
        fname, initialized = self._init_filepath(filepath, self._default_source_name)
        if len(self._rw) == 0:
            self._w("/* No writable registers */")
            if self._fp is not None:
                self._fp.close()
            return
        if not initialized:
            self._source_init(fname, includes)
        self._w(f"\n{self._write_fn_sig} {{")
        self._w("  enum mb_reg_id id = (enum mb_reg_id)(mbRegId & 0xffff);")
        self._w("  int32_t mbData32 = (int32_t)(mbData & 0xffff);")
        self._w("  switch (id) {")
        for mb_name, (leep_name, is_upper) in self._rw.items():
            if leep_name is None:
                continue
            self._w(f"    case {mb_name}:")
            if is_upper:
                low_mb_name = self.get_low_mb_name(mb_name)
                self._w(f"      mbData32 = (mbData32 << 16) | (int32_t)mb_get_reg_map({low_mb_name});")
            self._w(f"      write_lb_reg({leep_name}, mbData32);")
            self._w("      break;")
        self._w("      default:")
        self._w("#ifdef MB_MEMORY_ALLOW_ALL_WRITES")
        self._w("#if MB_MEMORY_ALLOW_ALL_WRITES")
        self._w("          break;")
        self._w("#else // !MB_MEMORY_ALLOW_ALL_WRITES")
        self._w("          return;  // ignore the value for non-writable registers")
        self._w("#endif")
        self._w("#else // ndef MB_MEMORY_ALLOW_ALL_WRITES")
        self._w("          return;  // ignore the value for non-writable registers")
        self._w("#endif")
        self._w("  }")
        self._w("  mb_update_reg_map(id, mbData); // store the value for writable registers")
        self._w("  return;")
        self._w("}")
        if self._fp is not None:
            self._fp.close()
        return

    def get_high_mb_name(self, mb_name):
        return mb_name + "_HI"

    def get_low_mb_name(self, mb_name):
        if mb_name[-3:] == "_HI":
            return mb_name[:-3]
        raise Exception(f"No low LEEP name associated with {mb_name} (should end in '_HI' if it's an upper-halfword)")

    def gen_read_fn(self, filepath=None, includes=None):
        fname, initialized = self._init_filepath(filepath, self._default_source_name)
        if not initialized:
            self._source_init(fname, includes)
        ro = self._purge_lowers(self._addr_map.get("ro", []))
        rw = self._purge_lowers(self._addr_map.get("rw", []))
        todo = (
            (ro, "Read-Only Registers"),
            (rw, "Read-Write Registers"),
        )
        self._w(f"\n{self._read_fn_sig} {{")
        self._w("  int32_t val;")
        for _map, comment in todo:
            if len(_map) == 0:
                continue
            self._w(f"  /* {comment} */")
            for mb_name, (leep_name, is_upper) in _map.items():
                if leep_name is None:
                    continue
                self._w(f"  val = read_lb_reg({leep_name});")
                if is_upper:
                    low_mb_name = self.get_low_mb_name(mb_name)
                    self._w(f"  mb_update_reg_map({low_mb_name}, val & 0xffff);")
                    self._w(f"  mb_update_reg_map({mb_name}, val>>16);")
                else:
                    self._w(f"  mb_update_reg_map({mb_name}, val);")
        self._w("  return;\n}")
        if self._fp is not None:
            self._fp.close()
        return

    def _purge_lowers(self, dd):
        """For any entries that are beyond 16-bit (have 'uppers'), remove the lower entry in the dict."""
        _map = dd.copy()
        to_pop = []
        for mb_name, (leep_name, is_upper) in dd.items():
            if is_upper:
                to_pop.append(self.get_low_mb_name(mb_name))
        for mb_name in to_pop:
            del _map[mb_name]
        return _map

    def gen_source(self, filepath=None, includes=None):
        self.gen_write_fn(filepath)
        self.gen_read_fn(filepath)
        return


def test_header(filepath):
    cg = CGenerator(filepath)
    cg.gen_header()
    return


def test_source(filepath):
    cg = CGenerator(filepath)
    cg.gen_source()
    return


def main():
    import argparse
    parser = argparse.ArgumentParser("Modbus address mapper.")
    parser.add_argument("toml_reg_map", help="Modbus-to-LEEP register map in TOML syntax.")
    parser.add_argument("--header", default=0, nargs="?", help="C header file name.")
    # if "--header" is not included, the value will be 0
    # if "--header" is passed by itself, the value will be None.
    # if "--header foo" is passed, the value will be "foo"
    parser.add_argument("-c", "--source", default=0, nargs="?", help="C source file name.")
    parser.add_argument("-I", "--include", default=None, action="append",
                        help="Header files to include in auto-generated source file.")
    # Same with "--source"
    args = parser.parse_args()
    cg = CGenerator(args.toml_reg_map)
    if args.include is not None:
        for include in args.include:
            cg.add_include(include)
    if args.header != 0:
        cg.gen_header(args.header)
    if args.source != 0:
        cg.gen_source(args.source)
    return 0


if __name__ == "__main__":
    __THIS_FILE__ = os.path.split(sys.argv[0])[1]
    exit(main())
    # toml_test(sys.argv[1])
    # test_header(sys.argv[1])
    # test_source(sys.argv[1])
