# Forwarder kept for one release: moved to soc/common/sim/.
.PHONY: all $(MAKECMDGOALS)
all $(MAKECMDGOALS):
	@echo "soc/marble_zest/sim is deprecated; use make -C soc/common/sim"
	$(MAKE) -C ../../common/sim $@
