# Forwarder kept for one release: moved to soc/common/synth/.
.PHONY: all $(MAKECMDGOALS)
all $(MAKECMDGOALS):
	@echo "soc/marble_zest/synth is deprecated; use make -C soc/common/synth"
	$(MAKE) -C ../../common/synth $@
