name: uspas_llrf
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.29.5
  - jupyter_core=5.8.1
  - pip=25.2
  - python=3.13.5
  - pip:
      - cocotb==1.9.2
      - cocotb-bus==0.2.1
      - matplotlib==3.10.5
      - numpy==2.3.2
      - pandas==2.3.1
      - pyserial==3.5
      - pytest==8.4.1
      - scipy==1.16.1
      - git+https://github.com/BerkeleyLab/leep.git
