include ../../dir_list.mk
FSET := USPAS

include $(TOP)settings.mk
include $(BUILD_DIR)/top_rules.mk
include $(BUILD_DIR)/newad_top_rules.mk
include $(APP_DSP_DIR)/rules.mk
include $(BUILD_DIR)/bottom_rules.mk
