# Forwarder kept for one release: moved to soc/common/top_sim/.
.PHONY: all $(MAKECMDGOALS)
all $(MAKECMDGOALS):
	@echo "soc/marble_zest/top_sim is deprecated; use make -C soc/common/top_sim"
	$(MAKE) -C ../../common/top_sim $@
